services:
  customer-service:
    #    build: employees-service
    build: Customer-service
    hostname: customer-service
    ports:
      - "7002:7002"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      mysql2:
        condition: service_healthy

  mysql2:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customer-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secretpwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3302:3302"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-psecretpwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10



  delivery-service:
    #    build: employees-service
    build: Delivery-service
    hostname: delivery-service
    ports:
      - "7003:7003"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      mysql3:
        condition: service_healthy

  mysql3:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=delivery-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secretpwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3303:3303"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-psecretpwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10



  photo-service:
    #    build: employees-service
    build: Photo-service
    hostname: photo-service
    ports:
      - "7001:7001"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      mysql1:
        condition: service_healthy

  mysql1:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=photo-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secretpwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3301:3301"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-psecretpwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10


