services:
  customer-service:
    #    build: employees-service
    build: .
    hostname: customer-service
    ports:
      - "7002:7002"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      mysql2:
        condition: service_healthy

  mysql2:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customer-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secretpwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3302:3302"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-psecretpwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

